version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/code
    ports:
      - 8000:8000
    tty: true
    working_dir: /code/app
    command: python manage.py runserver 0.0.0.0:8000 #webサーバー起動
