# Generated by Django 4.2 on 2023-04-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_app', '0002_post_file_path_post_result_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Target',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
