# Generated by Django 4.2 on 2023-04-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict_app', '0003_post_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Target',
        ),
    ]
